default:

development:
  amadeus:
    key: '<amadeus user api key>'
    secret: '<amadeus user api secret>'
    root_url: 'https://test.api.amadeus.com'
  database:
    drivername: 'postgresql+psycopg2'
    username: 'dev_user'
    password: 'pass'
    host: 'localhost'
    port: 5432
    database: 'dev_db'

testing:
  database: null  # this should not be used during testing
  test_db:
    drivername: 'postgresql+psycopg2'
    username: 'test_user'
    password: 'pass'
    host: 'localhost'
    port: 5433
    # database: # This is filled dynamically during runtime
  cleanup_database_name: 'test_cleanup_db'

production:

global:

