default:

development:
  database:
    drivername: 'postgresql+psycopg2'
    username: '...'
    password: '...'
    host: '...'
    port: ...
    database: '...'

testing:
  database:
    drivername: 'postgresql+psycopg2'
    username: '...'
    password: '...'
    host: '...'
    port: ...
    database: '...'
  cleanup_database:
    drivername: 'postgresql+psycopg2'
    username: '...'
    password: '...'
    host: '...'
    port: ...
    database: '...'

production:

global:

