default:
  logging:
    version: 1

    # DEFAULT LOGGING FORMATTERS
    formatters:
      brief:
        format: '%(asctime)s %(levelname)-8s: %(message)s'
        datefmt: '%H:%M:%S'
      precise:
        format: '%(asctime)s %(levelname)-8s: %(name)s[%(lineno)s]: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

    # DEFAULT LOGGING HANDLERS
    handlers:
      brief_console_handler:
        class : logging.StreamHandler
        formatter: brief
        level: WARN
        stream  : ext://sys.stdout
      precise_console_handler:
        class : logging.StreamHandler
        formatter: precise
        level: WARN
        stream  : ext://sys.stdout
      sqlalchemy_console_handler:
        class : logging.StreamHandler
        formatter: brief
        level: WARN
        stream  : ext://sys.stdout
      sqlalchemy_rotating_file_handler:
        class : logging.handlers.RotatingFileHandler
        formatter: precise
        level   : DEBUG
        filename: sqlalchemy.log
        maxBytes: 1000000
        backupCount: 3

    # DEFAULT LOGGERS
    loggers:
      sqlalchemy: 
        propagate: false
        level: DEBUG
        handlers: 
          - sqlalchemy_rotating_file_handler
      sqlalchemy.engine: {propagate: true, level: DEBUG}
      sqlalchemy.pool: {propagate: true, level: DEBUG}
      sqlalchemy.dialects: {propagate: true, level: DEBUG}
      sqlalchemy.orm: {propagate: true, level: DEBUG}


development:
  logging:
    dynaconf_merge: true
    handlers:
      development_rotating_file_handler:
        class : logging.handlers.RotatingFileHandler
        formatter: precise
        level   : DEBUG
        filename: debug.log
        maxBytes: 1000000
        backupCount: 3
    root:
      level: DEBUG
      handlers: 
        - brief_console_handler
        - development_rotating_file_handler

testing:
  logging:
    dynaconf_merge: true
    handlers:
      testing_console_handler:
        class : logging.StreamHandler
        formatter: precise
        level: WARN
        stream  : ext://sys.stdout
    # loggers:
      # sqlalchemy: {level: WARN}
      # sqlalchemy.engine: {level: WARN}
      # sqlalchemy.pool: {level: WARN}
      # sqlalchemy.dialects: {level: WARN}
      # sqlalchemy.orm: {level: WARN}
    root:
      level: WARN
      handlers: 
        - testing_console_handler

production:

global:

