default:
    env_name: default
    default_logger_name: 'jormungand.default_logger'

development:
    env_name: development
    db_echo: true

testing:
    env_name: testing

production:
    env_name: production

global:
    global_env_name: global

